### ISSUE TITLE
IPay88 payment mehod wan't load on checkout.

### ISSUE THREAD

**Issue by im-jc** [mage2pro/ipay88#15]
Hi!
Magento 2.2.3
php-mysql - Latest verions

I have installed iPay88 extesnion using composer. I have many stores in my site.
But for malaysia i installed iPay88 for payment method. But is wan't load on checkout page.
I have selected default country as malaysia for malaysia store and enable this method for malaysia store with correct `Live Merchant Code` and `Live Merchant Key`.

I can see loader.js of iPay88 is loading but no payment method.
I am attaching the settings of iPay88. 
![ipay88](https://user-images.githubusercontent.com/37610990/44297020-6f1b3800-a2e7-11e8-92eb-e0b7c5272ab3.png)

Please suggest solution or am i missing someting?
Thanks a lot

**Comment by dmitrii-fediuk** [comment]
What is your website?

**Comment by im-jc** [comment]
Here is my website with my product link.
https://beta.directsales.io/malaysia_en/test123.html

**Comment by dmitrii-fediuk** [comment]
You need to buy a license here: [mage2.pro/t/2775](https://mage2.pro/t/2775)

**Comment by im-jc** [comment]
My client already bought license. Do you provide licence key or something that should be set to magento 2 admin ?? 
There is a line "You can try it before buy". What does that mean? Can i try it? I am using aheadworks opc.
Can you please tell me what error did you find so that you provide 'buy licence' as solution.  Am i missing something in settings? Please let me know.

**Comment by im-jc** [comment]
Why did you close ticket? Please open. I did not solution yet.

**Comment by dmitrii-fediuk** [comment]
Nobody bought the license to the **directsales.io** website.
