### ISSUE TITLE
Could not save child: "Unknown entity type: Magento\Bundle\Model\Selection\Interceptor requested"

### ISSUE THREAD

**Issue by ghost** [mage2pro/ipay88#17]
Magento ver. 2.2.3
mage2pro/ipay88 1.6.0

When trying to save a bundle product with items I get the following error:

Could not save child: "Unknown entity type: Magento\Bundle\Model\Selection\Interceptor requested"

**Comment by dmitrii-fediuk** [comment]
Please provide your website's URL.

**Comment by ashishjob0424** [comment]
@jaystewart
HAve you gt any solution on this?

**Comment by ghost** [comment]
Not that I can remember. Sorry.

**Comment by Malaz951** [comment]
Any solution for this issue?
I face it also in Magento 2.3.5-p

**Comment by dmitrii-fediuk** [comment]
You can hire me in Upwork to solve any issue with my module: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)
