### ISSUE TITLE
Ipay88 Extension issue after payment Success

### ISSUE THREAD

**Issue by srinivas-entropia** [mage2pro/ipay88#19]
HI,

Please find the attachment.

We have integrated Ipay88 Magento extension. Extension is working successful till the payment complete, once the payment Complete it redirects to success page but success page is not loading the Transaction information (like Transaction Id, Transaction amount, Etc…) and Success page not loading the Website Header and footer (Please refer attachment).

Please help us with this issue ASAP.

Thanks & Regards,
Srinivas Gundali
+60169706474
Email : srinivas.gundali@entropia.com
Skype : srinivas.gundale1
![IMG-20200921-WA0000](https://user-images.githubusercontent.com/54976810/93735732-889eb480-fc10-11ea-96e7-af8c1f713fb3.jpg)

**Comment by dmitrii-fediuk** [comment]
Hire me in Upwork to solve your problems: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro).
I do not support the module for free.
