### ISSUE TITLE
file not found \Df\PaypalClone\Method

### ISSUE THREAD

**Issue by sivass** [mage2pro/ipay88#2]
Hi, when i try to install ur plugin on my magento2.1 version it will show error that file not found  \Df\PaypalClone\Method  please help me..

**Comment by dmitrii-fediuk** [comment]
Please [buy the license](https://mage2.pro/t/2775) first before asking for support.  
Moreover, I provide a totally free [installation service](https://mage2.pro/t/3585) after the purchase.
