### ISSUE TITLE
"Declaration of X must be compatible"

### ISSUE THREAD

**Issue by Berman59** [mage2pro/ipay88#21]
May I ask if this module (and mage2pro/core) is compatable (or would be updated to be) with M2.4.5 + PHP8.1? I tried updating a dev site to 2.4.5 from 2.3.7 and the module is triggering a number of "Declaration of X must be compatible" errors. I also noticed zendframework is no longer loaded in Magento 2.4.5, but is still required by mage2pro/core.

**Comment by mahadekhan** [comment]
This module is not compatible with 2.4.3+. Please release an update with the compatible issue.

**Comment by Berman59** [comment]
@mahadekhan not sure if this works for you or not, but I eventually contacted support@ipay88.com.my and they sent me their own version of Magento payment plugin, which works on 2.4.3 and 2.4.4 (tested; supposed to work on 2.4.4+ too)
(contact is different if yor have merchant ID for ipay88 Indonesia ([cs@ipay88.co.id](mailto:cs@ipay88.co.id)) instead of Malaysia)

**Comment by dmitrii-fediuk** [comment]
Fixed in [`mage2pro/core` 9.5.2](https://github.com/mage2pro/core/releases/tag/9.5.2).
