### ISSUE TITLE
Whether the «Public bank» is supported?

### ISSUE THREAD

**Issue by darkredz** [mage2pro/ipay88#6]
we notice that in myr.json there is a list of banks
{
	"2": "Credit Card (MYR)"
	,"6": "Maybank2U"
	,"8": "Alliance Online"
	,"10": "AmOnline"
	,"14": "RHB Online"
	,"15": "Hong Leong Online"
	,"20": "CIMB Click"
	,"22": "Web Cash"
	,"48": "PayPal (MYR)"
	,"100": "Celcom AirCash"
	,"102": "Bank Rakyat Internet Banking"
	,"103": "affinOnline"
	,"134": "Bank Islam"
	,"152": "UOB"
	,"166": "Bank Muamalat"
	,"167": "OCBC"
	,"168": "Standard Chartered Bank"
}

Is other payment options supported by iPay88 supported by this plugin? For instance there is no public bank in this list. How can we add more support for different options ?

**Comment by dmitrii-fediuk** [comment]
The «**Public bank**» payment option is absent in the iPay88's «[Technical Specification v1.6.2 (for Malaysia Only)](https://mage2.pro/t/topic/3682)». 
Please use the module's forum branch for such questions: https://mage2.pro/c/extensions/ipay88
Use the GitHub's issue tracker for bugs only.
