### ISSUE TITLE
[Magento 2.2 / 2.3] The iPay88 module shows the «Please agree to all the terms and conditions before placing the order» warning even if the terms and conditions checkbox is checked

### ISSUE THREAD

**Issue by codekipple** [mage2pro/ipay88#7]
Hi,
I'm attempting to upgrade a site using this module to magento version 2.2.2. After upgrading I'm having an issue where I cannot get past the checkout page.

After picking a payment option, checking the terms and conditions checkbox and clicking the 'Place Order' button it fails to re-direct me and just keeps showing the error message 'Please agree to all the terms and conditions before placing the order.' despite the fact that I have checked the terms and conditions checkbox.
![screen_shot_2018-01-08_at_16_38_21](https://user-images.githubusercontent.com/221714/34681123-ba950c74-f492-11e7-97b6-252612d19dd6.png)

I tried reverting the codebase back to the current Magento version the site is using (2.1.7) and the plugin again works as normal. I'm not sure when the functionality of the agreementsValidator code has changed between 2.1.7 and 2.2.2.

I've been looking into the issue but not having much luck so far. The part of Magento that creates the error message is `vendor/magento/module-checkout-agreements/Model/Checkout/Plugin/GuestValidation.php` line 104.

It may be only a problem with this site because of other 3rd party code rather than your plugin. I was just wondering if you have checked compatibility with Magento 2.2.2?

Thanks very much,
Carl

**Comment by dmitrii-fediuk** [comment]
Provide the problem website URL.

**Comment by dmitrii-fediuk** [comment]
I support only the paying customers.

**Comment by codekipple** [comment]
A colleague has emailed you at admin@mage2.pro providing the website URL.

**Comment by dmitrii-fediuk** [comment]
Yes, I have reproduced the issue with **Magento 2.3**.
I will fix it today.
![01](https://user-images.githubusercontent.com/83204/34917578-8f186e94-f972-11e7-80ff-638895b4aaee.png)

**Comment by dmitrii-fediuk** [comment]
It is not my module's issue.
It is a Magento 2.2 core issue: https://github.com/magento/magento2/issues/11885
It is already fixed at **[2017-12-19](https://github.com/magento/magento2/pull/12401/commits/a35b4686)** in the [`2.2-develop`](https://github.com/magento/magento2/tree/2.2-develop) branch: https://github.com/magento/magento2/pull/12401
So you need just to wait for the next Magento 2.2 release, or use the latest development code.

**Comment by dmitrii-fediuk** [comment]
Today I have analysed the Magento team's fix above and I have noticed that it fixes only the PayPal module despite the fact that a lot of third-party payment modules are broken too.
So I have implemented [my own fix for all my payment modules](https://github.com/mage2pro/core/issues/65) and I have included it to the **[3.6.0](https://github.com/mage2pro/core/releases/tag/3.6.0)** version of my [`mage2pro/core`](https://github.com/mage2pro/core) package.

**Comment by codekipple** [comment]
Ah cool thanks Dmitry.

**Comment by topranavp** [comment]
@codekipple , can you share the fix as I have used Payu module and that is also broken after upgrade to M2.2.3

Here is its URL, https://github.com/payu-india/PayUbiz_Magento/tree/ver2.x

**Comment by dmitrii-fediuk** [comment]
I can implement the same fix for the Payumoney module for **$150**.

**Comment by topranavp** [comment]
Ohhh, @dmitry-fedyuk can't you share the solution? I really appreciate if you share the same.

**Comment by dmitrii-fediuk** [comment]
Banned.

**Comment by david-fiaty-cko** [comment]
Hi Dmitry, we have clients complaining because of the T&C blocking the checkout. They tend to think it's a third party module issue. Could you please confirm if this is indeed a Magento 2 core bug?

**Comment by dmitrii-fediuk** [comment]
Provide me exact URL to your website.

**Comment by david-fiaty-cko** [comment]
I don't have client websites links, just dealing with M2 core: http://151.80.61.232/m224
Our payment method is the only one available on the payment page apart from the core ones.

**Comment by dmitrii-fediuk** [comment]
This website does not use any of my modules.

**Comment by david-fiaty-cko** [comment]
Yes I know, just asking if you think this is a core M2 bug.

**Comment by dmitrii-fediuk** [comment]
I can fix it for **$200**.

**Comment by david-fiaty-cko** [comment]
Ok it's something we can discuss, I will talk to our line manager. But in order to defend the case, I have to know if this a core M2 bug we are trying to find a workaround for, or if it a third party module issue.

**Comment by dmitrii-fediuk** [comment]
Banned too.
Fuck off all non-payers.
